Repository waywardware/vigilant-fiesta, pull requests merged in 2018-10, with the labels that each got.

#36 [Issue-35] Making dev work in windows
  package.json
Labels: bug

#37 Making some changes to the compiled folder
  .gitignore
  dist/assets/Animals/fox-sprite.png
  dist/assets/Animals/pig-sprite.png
  dist/assets/Animals/racoon-sprite.png
  dist/assets/Animals/sheep-sprite.png
  package-lock.json
  package.json
  rollup.config.js
Labels: assets, bug

#34 Basic App icon design Issue #31
  .gitignore
  dist/assets/Icons/eco-icon.png
  src/main/Main.ts
Labels: assets

#33 [Issue 11] game engine
  .gitignore
  package-lock.json
  package.json
  rollup.config.js
  src/common/engine/GameEngine.ts
  src/common/engine/Render.ts
  src/common/entities/Animal.ts
  src/common/entities/Animals.ts
  src/common/entities/EntityInterfaces.ts
  src/common/utils/Constants.ts
  src/common/utils/Styles.ts
  src/renderer/index.html
  src/renderer/views/ApplicationComponent.tsx
  src/renderer/views/CanvasComponent.tsx
  src/renderer/views/SmallButtonComponent.tsx
  src/renderer/views/SpeedControlComponent.tsx
  test/common/engine/GameEngine_spec.ts
  test/common/engine/Render_spec.ts
  test/common/entities/Animal_spec.ts
  tsconfig.json
  tslint.json
Labels: enhancement

#43 [Issue-42] Clean up branch
  dist/assets/Animals/fox-sprite.png
  dist/assets/Animals/pig-sprite.png
  dist/assets/Animals/racoon-sprite.png
  dist/assets/Animals/sheep-sprite.png
  dist/assets/Icons/eco-icon.png
  package-lock.json
  package.json
  rollup.config.js
  src/common/engine/GameEngine.ts
  src/common/engine/Render.ts
  src/common/entities/Animal.ts
  src/common/entities/Animals.ts
  src/common/entities/EntityInterfaces.ts
  src/coreElectron/Main.ts
  src/pages/Index.tsx
  src/renderer/index.html
  src/views/ApplicationComponent.tsx
  src/views/SmallButtonComponent.tsx
  src/views/SpeedControlComponent.tsx
  test/common/engine/GameEngine_spec.ts
  test/common/engine/Render_spec.ts
  tsconfig.json
  tslint.json
Labels: tech debt

#44 Adding contributors
  package.json
Labels: documentation

#41 Plant species added
  src/common/entities/Plant.ts
  src/common/entities/Plants.ts
Labels: enhancement

#40 Title name change
  .gitignore
  dist/static/images/icons/eco-icon.png
  dist/static/images/sprites/animals/fox-sprite.png
  dist/static/images/sprites/animals/pig-sprite.png
  dist/static/images/sprites/animals/racoon-sprite.png
  dist/static/images/sprites/animals/sheep-sprite.png
  dist/static/index.html
  src/coreElectron/Main.ts
Labels: enhancement

#38 Added Angel as an author to the readme
  README.md
Labels: documentation
