Repository waywardware/vigilant-fiesta, pull requests merged in 2018-09, with the labels that each got.

#9 [Issue 2] Lets get a render working
  package-lock.json
  package.json
  src/basepath.ts
  src/common/Animal.ts
  src/common/engine/Render.ts
  src/common/utils/Constants.ts
  src/common/utils/Styles.ts
  src/main/Main.ts
  src/renderer/Renderer.tsx
  src/renderer/index.html
  src/renderer/views/ApplicationComponent.tsx
  src/renderer/views/CanvasComponent.tsx
  test/Main.ts
  test/common/engine/Render_spec.ts
  tsconfig.json
  tslint.json
  webpack.config.js
Labels: enhancement

#13 [Issues 12] Adding animal class and tests
  src/common/Animal.ts
  src/common/engine/Render.ts
  src/common/entities/Animal.ts
  src/common/entities/Animals.ts
  src/common/entities/EntityInterfaces.ts
  src/common/entities/Plants.ts
  src/main.ts
  src/renderer/views/CanvasComponent.tsx
  test/common/entities/Animal_spec.ts
Labels: enhancement, test-coverage

#17 Update .travis.yml
  .travis.yml
Labels: enhancement

#15 Update README.md
  README.md
Labels: documentation

#20 [Issue 19] rollup
  .gitignore
  package-lock.json
  package.json
  rollup.config.js
  src/basepath.ts
  src/main/Main.ts
  webpack.config.js
Labels: enhancement

#32 Added Animal Art Sprites #30
  assets/Animals/fox-sprite.png
  assets/Animals/pig-sprite.png
  assets/Animals/racoon-sprite.png
  assets/Animals/sheep-sprite.png
Labels: assets
